version: '3'
services:
  bfextractor:
    build: .
    environment:
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      STACKPREFIX: minerva-test
      STAGE: dev
      DEBUG: "True"
    volumes:
      - /data:/tmp/aws
    command:
      # Import UUID and also the directory name within /data
      - daa4fc5e-e3de-4d5a-b744-6672e784d2df
      # Location of entrypoint within importUuid directory
      - ashlar_examples/BP40.ome.tif
      # Identify for the Bio-Formats Reader
      - loci.formats.in.OMETiffReader
      # Reader Software Name
      - Bio-Formats
      # Reader Software Version
      - UNKNOWN
      # Bucket in which to write tiles
      - thejohnhoffer-bfextractor-test
      # BFU UUID
      - ca6d604a-3220-47e5-94c6-277d99c57b45
